"""LaTeX table emission helpers for T1–T5 — paper_plan_v2 §9, §16 P10.

Tables are emitted as bare booktabs `tabular` blocks meant to be `\\input` from
paper/main.tex (the float wrapper + caption live in the paper source; numbers
never do — every cell traces to a results CSV via the generating script, whose
name and source CSV are stamped into a comment header).
"""

from __future__ import annotations

from pathlib import Path

_ESCAPE = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(s: str) -> str:
    return "".join(_ESCAPE.get(ch, ch) for ch in str(s))


def fmt_num(x, digits: int = 2, dollar: bool = False) -> str:
    """Format a numeric cell; NaN/None → '--'."""
    try:
        import math
        if x is None or (isinstance(x, float) and math.isnan(x)):
            return "--"
        v = f"{float(x):.{digits}f}"
        return rf"\${v}" if dollar else v
    except (TypeError, ValueError):
        return tex_escape(x)


def fmt_ci(point, lo, hi, digits: int = 2, dollar: bool = False) -> str:
    """`point [lo, hi]` — 95% bootstrap CI convention of §5.6."""
    p, l, h = (fmt_num(v, digits, dollar) for v in (point, lo, hi))
    if p == "--":
        return "--"
    return f"{p} [{l}, {h}]"


def write_tabular(
    out_path: str | Path,
    colspec: str,
    header: list[str],
    rows: list[list[str]],
    *,
    script: str,
    source_csv: str,
    midrules_before: tuple[int, ...] = (),
) -> Path:
    """Write a booktabs tabular .tex file. `rows` cells are already-formatted
    strings (escape text cells with tex_escape at the call site).
    `midrules_before` = row indices that get a \\midrule above them (group
    separators, e.g. domain blocks)."""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"% AUTO-GENERATED by {script} from {source_csv} — do not hand-edit (§16 P10).",
        f"\\begin{{tabular}}{{{colspec}}}",
        "\\toprule",
        " & ".join(header) + r" \\",
        "\\midrule",
    ]
    for i, row in enumerate(rows):
        if i in midrules_before and i > 0:
            lines.append("\\midrule")
        lines.append(" & ".join(row) + r" \\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))
    print(f"[{script}] wrote {out}")
    return out
